package com.hausontech.hrs.daoImpl;

import javax.annotation.Resource;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

public class BaseDaoImpl {
	@Resource
	protected JdbcTemplate jdbcTemplate;
	@Resource
	protected NamedParameterJdbcTemplate namedjdbcTemplate;
	
	protected final String AUDIT_QUERY_STRING = ", CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY ";
	/**
	 * @return the jdbcTemplate
	 */
	
	public JdbcTemplate getJdbcTemplate() {
		return jdbcTemplate;
	}
	
	/**
	 * @param jdbcTemplate the jdbcTemplate to set
	 */
	
	public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
		this.jdbcTemplate = jdbcTemplate;
	}
	
	/**
	 * @return the namedjdbcTemplate
	 */
	
	public NamedParameterJdbcTemplate getNamedjdbcTemplate() {
		return namedjdbcTemplate;
	}
	
	/**
	 * @param namedjdbcTemplate the namedjdbcTemplate to set
	 */
	
	public void setNamedjdbcTemplate(NamedParameterJdbcTemplate namedjdbcTemplate) {
		this.namedjdbcTemplate = namedjdbcTemplate;
	}
	
	public StringBuffer pageSql(StringBuffer sql_in, int start, int count) {		
			StringBuffer sql = new StringBuffer();
			sql.append(" SELECT * FROM (");
			sql.append("     select * from (");
			sql.append(sql_in);
			sql.append("                ) innerA ");
			sql.append("          where innerA.row_number >= " + start + ") outerB ");
			sql.append("  where rownum <= " + count + " ");
			return sql;
	}
	
	public long getAutoGeneratedPrimaryKey(String sequenceName) {
		StringBuffer sql = new StringBuffer();
		sql.append("SELECT ");
		sql.append(sequenceName);
		sql.append(".Nextval FROM DUAL");
		return (long)namedjdbcTemplate.getJdbcOperations().queryForObject(sql.toString(), long.class);
	}
	
	
}
